default: mysql
logging: false

databases:
  - name: mysql
    driver: mysql
    host: 127.0.0.1
    port: 3306
    database: gin
    username: root
    password: 
    charset: utf8mb4
    prefix:
    