name: gofmt
on:
  push:
    branches-ignore:
    - staging
    - production
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4

