name: lint
on:
  push:
    branches-ignore:
    - staging
    - production
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: dominikh/staticcheck-action@v1.2.0